apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../common/deployment
  - metrics-hpa.yml
  #- custom-hpa.yml
  #- external-hpa.yml
namePrefix: bff-
commonLabels:
  microservice: bff
configMapGenerator:
  - name: app-config
    behavior: merge
    files:
      - application-custom.yaml
images:
  - name: microservice
    newName: factory-registry.cloudzcp.io/edu999/awesome-bff-service
    newTag: 0.1.0