apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../overlay/dev/bff
configMapGenerator:
  - name: app-config
    behavior: merge
    files:
      - application-test.yaml
images:
  - name: microservice
    newName: factory-registry.cloudzcp.io/edu999/awesome-bff-service
    newTag: latest