apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: app
        image: microservice
        ports:
        - containerPort: 8080
        resources:        
          limits:
            cpu: "100m"
            memory: "256Mi"
        volumeMounts:
        - mountPath: /config
          name: app-config-volume
      volumes:
      - name: app-config-volume
        configMap:
          name: app-config