apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../common/deployment
namePrefix: order-
commonLabels:
  microservice: order
configMapGenerator:
  - name: app-config
    behavior: merge
    files:
      - application-custom.yaml
images:
  - name: microservice
    newName: factory-registry.cloudzcp.io/edu999/awesome-order-service
    newTag: 0.1.0