server:
  port: 8081

spring:
  application:
    name: bff-app
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      save-mode: always
      namespace: spring:test
  redis:
    port: 6379
    host: localhost
    password: password
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
        max-wait: 30
    database: 0
  thymeleaf:
    prefix: classpath:/static/html/
  cloud:
    kubernetes:
      reload:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

api:
  account:
    url: http://account-app-v0-dev:8080
  accountbank:
    url: http://account-app-v0-dev:8080
  cart:
    url: http://cart-app-v0-dev:8080
  category:
    url: http://category-app-v0-dev:8080
  order:
    url: http://order-app-v0-dev:8080
  payment:
    url: http://payment-app-v0-dev:8080
  product:
    url: http://product-app-v0-dev:8080

awesome:
  title: null